builders:
  widgetStudioGenerator:
    import: "package:generators/builder.dart"
    builder_factories: ["generateWidgetStudio"]
    build_extensions: { ".dart": [".widget_studio_generator.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]


