name: widget_studio
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  annotations:
    path: ./../annotations

  generators:
    path: ./../generators

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0

  flutter_test:
    sdk: flutter
