name: generators
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  build: ^2.2.1
  source_gen: ^1.2.1

  annotations:
    path: ./../annotations

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0

  flutter_test:
    sdk: flutter
